### ISSUE TITLE
Profile name

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [kixell/rudder_pedals#1]
Hi I would like to exchange with you as you use a name for your profile (KIXELL) that is the name of my company.
I opened a ticket with Github to this subject. Could you please rename your account ?

**Comment by kixell** [comment]
Sorry, I've used this name across multiple platforms and I'd prefer not to change my username.

**Comment by Kixell-NicolasJardillier** [comment]
I understand but you can change the name of the organisation without loosing anything
